apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: vf-dev
spec:
  version: 8.10.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
