apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: vf-dev
spec:
  version: 8.10.2
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server:
      host: "0.0.0.0"
      ssl.enabled: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            httpGet:
              path: /login
              port: 5601
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold : 3
