apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: vf-dev
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        upstream auth_service {
            server auth-service:5000;
        }

        upstream analytics_service {
            server analytics-service:5000;
        }

        upstream workout_service {
            server workout-service:5000;
        }

        server {
            listen 80;

            location /auth/ {
                proxy_pass http://auth_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /analytics/ {
                proxy_pass http://analytics_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /workout/ {
                proxy_pass http://workout_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
