replicaCount: 1

app:
  name: analytics-service
  namespace: vf-dev
  environment: dev

image:
  repository: europe-west1-docker.pkg.dev/virtuafit/analytics-repo/analytics-service 
  tag: "latest"
  pullPolicy: Always

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: auth-service-psql-secret
        key: DATABASE_URL
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: jwt-secret-key
        key: SECRET_KEY
  - name: ELASTICSEARCH_HOST
    value: "quickstart-es-http.vf-dev.svc.cluster.local"
  - name: ELASTICSEARCH_PORT
    value: "9200"
  - name: ELASTICSEARCH_USER
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: quickstart-es-elastic-user
        key: elastic


service:
  type: ClusterIP
  port: 8080
  targetPort: 5000

probes:
  path: "/health"
  initialDelaySeconds: 10

imagePullSecrets: []