name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOOGLE_CLOUD_PROJECT: "virtuafit"
  TERRAGRUNT_WORKING_DIR: infrastructure/live/envs/dev
  GCP_REGION: "europe-west1"
  GKE_CLUSTER_NAME: "gke-dev"
  VPC_NAME: "vpc-dev"
  SUBNET_NAME: "subnet-dev"

jobs:
  setup-infrastructure:
    name: Setup GKE and VPC with Terraform and Terragrunt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}
          export_default_credentials: true

      - name: Install Terraform v1.9.5 and Terragrunt v0.67.1
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
          unzip terraform_1.9.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.67.1/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Terraform fmt (Formatting Check)
        run: |
          cd ${{ env.TERRAGRUNT_WORKING_DIR }}
          terraform fmt -check -recursive
          
      - name: Terragrunt fmt (Formatting Check)
        run: |
          cd ${{ env.TERRAGRUNT_WORKING_DIR }}
          terragrunt hclfmt --check

      - name: Terraform validate (Validation Check)
        run: |
          cd ${{ env.TERRAGRUNT_WORKING_DIR }}
          terraform validate

      - name: Terragrunt validate (Validation Check)
        run: |
          cd ${{ env.TERRAGRUNT_WORKING_DIR }}
          terragrunt validate

      - name: Terragrunt lint (Linting Check)
        run: |
          cd ${{ env.TERRAGRUNT_WORKING_DIR }}
          terragrunt validate-inputs

      - name: Initialize and apply Terragrunt for GKE and VPC
        run: |
          cd ${{ env.TERRAGRUNT_WORKING_DIR }}
          terragrunt init
          terragrunt apply -auto-approve --terragrunt-ignore-dependency-errors || echo "Resources already exist, skipping creation"
